Repository vgstation-coders/vgstation14, pull requests merged in 2024-12, with the labels that each got.

#3 faster move speed
  Content.Shared/Movement/Components/MovementSpeedModifierComponent.cs
  Content.Shared/StepTrigger/Components/StepTriggerComponent.cs
Labels: enhancement

#1 Readme
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#2 removes vent pump pressure lockout
  Content.Server/Atmos/Piping/Unary/Components/GasVentPumpComponent.cs
  Content.Server/Atmos/Piping/Unary/EntitySystems/GasVentPumpSystem.cs
  Content.Shared/Atmos/Piping/Unary/Components/SharedVentPumpComponent.cs
  Content.Shared/Atmos/Piping/Unary/Visuals/VentPumpVisuals.cs
  Resources/Locale/en-US/atmos/gas-vent-pump.ftl
Labels: enhancement

#5 removes atmos temperature caps
  Content.Client/Atmos/UI/GasThermomachineBoundUserInterface.cs
  Content.Server/Atmos/Commands/SetAtmosTemperatureCommand.cs
  Content.Server/Atmos/Commands/SetMapAtmosCommand.cs
  Content.Server/Atmos/Commands/SetTemperatureCommand.cs
  Content.Server/Atmos/EntitySystems/AtmosphereSystem.LINDA.cs
  Content.Server/Atmos/Reactions/GasReactionPrototype.cs
  Content.Shared/Atmos/Atmospherics.cs
  Content.Shared/Atmos/GasMixture.cs
Labels: enhancement

#6 Adds Asimov lawset for silicons, and makes it default
  Resources/Locale/en-US/station-laws/laws.ftl
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/Entities/Stations/nanotrasen.yml
  Resources/Prototypes/silicon-laws.yml
Labels: enhancement

#9 atmos gas interaction reworks
  Content.Server/Atmos/EntitySystems/AtmosphereSystem.Hotspot.cs
  Content.Server/Atmos/IGasReactionEffect.cs
  Content.Server/Atmos/Reactions/AmmoniaOxygenReaction.cs
  Content.Server/Atmos/Reactions/AmoniaOxygen_fire.cs
  Content.Server/Atmos/Reactions/FrezonCoolantReaction.cs
  Content.Server/Atmos/Reactions/FrezonOxygen_dissapation.cs
  Content.Server/Atmos/Reactions/FrezonPlasma_cooldown.cs
  Content.Server/Atmos/Reactions/FrezonProductionReaction.cs
  Content.Server/Atmos/Reactions/Frezon_decompose.cs
  Content.Server/Atmos/Reactions/N2ODecompositionReaction.cs
  Content.Server/Atmos/Reactions/N2O_hightemp_decompose.cs
  Content.Server/Atmos/Reactions/PlasmaFireReaction.cs
  Content.Server/Atmos/Reactions/PlasmaOxygen_to_fire_reaction.cs
  Content.Server/Atmos/Reactions/PlasmaSteam_to_Tritium.cs
  Content.Server/Atmos/Reactions/TritiumFireReaction.cs
  Content.Server/Atmos/Reactions/TritiumOxygen_fire.cs
  Content.Server/Atmos/Reactions/_reaction_helper_functions.cs
  Content.Server/IgnitionSource/IgnitionSourceComponent.cs
  Content.Server/Light/EntitySystems/MatchstickSystem.cs
  Content.Server/StationEvents/Events/GasLeakRule.cs
  Content.Server/Tools/ToolSystem.cs
  Content.Shared/Atmos/Atmospherics.cs
  Resources/Prototypes/Atmospherics/reactions.yml
Labels: enhancement

#14 Adjusts Command jobs to be Human only
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Labels: Consistency Issue, Balance

#17 greatly reduces job requirments
  Resources/Prototypes/Roles/Antags/nukeops.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Roles/Jobs/Science/borg.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
Labels: Balance

#19 Revert "Adjusts Command jobs to be Human only (#14)"
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Labels: IT'S A FEAAAATUUUUREEEEEEEEE

#20 pulling things no longer takes up a hand
  Content.Shared/Movement/Pulling/Components/PullerComponent.cs
Labels: Tweak

#28 fixes failing checks
  Content.IntegrationTests/Tests/Movement/PullingTest.cs
Labels: size/XS, S: Untriaged

#21 Janitorial changes
  Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
  Resources/Audio/Weapons/whip.ogg
  Resources/Locale/en-US/fluids/components/absorbent-component.ftl
  Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
  Resources/Prototypes/SoundCollections/hit_impacts.yml
Labels: Content, ss13 parity

#26 crafting menu fuzzy search framework
  Content.Client/Construction/UI/ConstructionMenu.xaml
  Content.Client/Construction/UI/ConstructionMenu.xaml.cs
  Content.Client/Construction/UI/ConstructionMenuPresenter.cs
  Content.Shared/Construction/Prototypes/ConstructionPrototype.cs
Labels: UI, size/S, Changes: UI

#29 fuzzy searching improvments and also actuall entries
  Content.Client/Construction/UI/ConstructionMenuPresenter.cs
  Resources/Prototypes/Recipes/Construction/clothing.yml
  Resources/Prototypes/Recipes/Construction/furniture.yml
  Resources/Prototypes/Recipes/Construction/machines.yml
  Resources/Prototypes/Recipes/Construction/structures.yml
  Resources/Prototypes/Recipes/Construction/tools.yml
  Resources/Prototypes/Recipes/Construction/utilities.yml
  Resources/Prototypes/Recipes/Construction/weapons.yml
Labels: S: Untriaged, size/M
